name: Test OIDC AWS Role Authentication

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main   # or your branch

jobs:
  test-auth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::107570342011:role/GitHubActions-ECR-Role
          aws-region: eu-west-1

      - name: Test AWS CLI access
        run: aws sts get-caller-identity

